const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=58',
  'https://sanand0.github.io/tdsdata/js_table/?seed=59',
  'https://sanand0.github.io/tdsdata/js_table/?seed=60',
  'https://sanand0.github.io/tdsdata/js_table/?seed=61',
  'https://sanand0.github.io/tdsdata/js_table/?seed=62',
  'https://sanand0.github.io/tdsdata/js_table/?seed=63',
  'https://sanand0.github.io/tdsdata/js_table/?seed=64',
  'https://sanand0.github.io/tdsdata/js_table/?seed=65',
  'https://sanand0.github.io/tdsdata/js_table/?seed=66',
  'https://sanand0.github.io/tdsdata/js_table/?seed=67',
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url);
    // Wait for the table to load (it's generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all cell text from the table, parse numbers, and sum them
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('table td');
      let sum = 0;
      cells.forEach(cell => {
        const val = parseFloat(cell.innerText);
        if (!isNaN(val)) sum += val;
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Total sum across all pages: ${grandTotal}`);
  await browser.close();
})();
